//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Labo.TwitterMiner.Video.Data
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    
    public partial class ContentCategory
    {
        public ContentCategory()
        {
            this.Contents = new HashSet<Content>();
            this.ContentCategory1 = new HashSet<ContentCategory>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> ParentID { get; set; }
        public bool IsActive { get; set; }
        public int SortOrder { get; set; }
        public string UserFriendlyUrl { get; set; }
    
        public virtual ICollection<Content> Contents { get; set; }
        public virtual ICollection<ContentCategory> ContentCategory1 { get; set; }
        public virtual ContentCategory ContentCategory2 { get; set; }
    }
}
