//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Labo.TwitterMiner.Video.Data
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    internal partial class ContentCategory_Mapping : EntityTypeConfiguration<ContentCategory>
    {
        public ContentCategory_Mapping()
        {					
    		this.HasKey(t => t.ID);		
    		this.ToTable("ContentCategory");
    		this.Property(t => t.ID).HasColumnName("ID");
    		this.Property(t => t.Name).HasColumnName("Name").IsRequired().IsUnicode(false).HasMaxLength(80);
    		this.Property(t => t.Description).HasColumnName("Description").IsUnicode(false).HasMaxLength(80);
    		this.Property(t => t.ParentID).HasColumnName("ParentID");
    		this.Property(t => t.IsActive).HasColumnName("IsActive");
    		this.Property(t => t.SortOrder).HasColumnName("SortOrder");
    		this.Property(t => t.UserFriendlyUrl).HasColumnName("UserFriendlyUrl").IsRequired().IsUnicode(false).HasMaxLength(255);
    		this.HasOptional(t => t.ContentCategory2).WithMany(t => t.ContentCategory1).HasForeignKey(d => d.ParentID);
    	}
    }
}
