//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Labo.TwitterMiner.Video.Data
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    
    public partial class VideoContent
    {
        public int ContentID { get; set; }
        public Nullable<int> ProviderID { get; set; }
        public string EmbedUrl { get; set; }
        public Nullable<long> ProviderViewCount { get; set; }
        public Nullable<double> ProviderRating { get; set; }
        public string ProviderUniqueID { get; set; }
        public Nullable<int> Duration { get; set; }
        public string Author { get; set; }
        public string Uploader { get; set; }
        public string BigPicture { get; set; }
        public string SmallPicture { get; set; }
        public string Description { get; set; }
        public Nullable<int> ProviderVoteCount { get; set; }
    
        public virtual Content Content { get; set; }
        public virtual VideoProvider VideoProvider { get; set; }
    }
}
