//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma warning disable 1573
namespace Labo.TwitterMiner.Video.Data
{
    using System;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HobbiesEntities : DbContext
    {
        static HobbiesEntities()
    	{ 
    		Database.SetInitializer<HobbiesEntities>(null);
    	}
    	
    	public HobbiesEntities() : base("name=HobbiesEntities")
        {
        }
    	
    	public HobbiesEntities(string nameOrConnectionString) : base(nameOrConnectionString)
    	{	
    	}
    
    	public HobbiesEntities(string nameOrConnectionString, DbCompiledModel model) : base(nameOrConnectionString, model)
    	{
    	}
    
    	public HobbiesEntities(DbConnection existingConnection, bool contextOwnsConnection) : base(existingConnection, contextOwnsConnection)
    	{
    	}
    
    	public HobbiesEntities(DbConnection existingConnection, DbCompiledModel model, bool contextOwnsConnection) : base(existingConnection, model, contextOwnsConnection)
    	{
    	}
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
    		modelBuilder.Conventions.Remove<IncludeMetadataConvention>();
    		modelBuilder.Configurations.Add(new Content_Mapping());
    		modelBuilder.Configurations.Add(new ContentCategory_Mapping());
    		modelBuilder.Configurations.Add(new ContentTag_Mapping());
    		modelBuilder.Configurations.Add(new VideoContent_Mapping());
    		modelBuilder.Configurations.Add(new VideoProvider_Mapping());
        }
    	
        public DbSet<Content> Contents { get; set; }
        public DbSet<ContentCategory> ContentCategories { get; set; }
        public DbSet<ContentTag> ContentTags { get; set; }
        public DbSet<VideoContent> VideoContents { get; set; }
        public DbSet<VideoProvider> VideoProviders { get; set; }
    }
}
