//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Labo.TwitterMiner.Video.Data
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    internal partial class VideoContent_Mapping : EntityTypeConfiguration<VideoContent>
    {
        public VideoContent_Mapping()
        {					
    		this.HasKey(t => t.ContentID);		
    		this.ToTable("VideoContent");
    		this.Property(t => t.ContentID).HasColumnName("ContentID").HasDatabaseGeneratedOption(DatabaseGeneratedOption.None);
    		this.Property(t => t.ProviderID).HasColumnName("ProviderID");
    		this.Property(t => t.EmbedUrl).HasColumnName("EmbedUrl").IsUnicode(false).HasMaxLength(2048);
    		this.Property(t => t.ProviderViewCount).HasColumnName("ProviderViewCount");
    		this.Property(t => t.ProviderRating).HasColumnName("ProviderRating");
    		this.Property(t => t.ProviderUniqueID).HasColumnName("ProviderUniqueID").IsUnicode(false).HasMaxLength(100);
    		this.Property(t => t.Duration).HasColumnName("Duration");
    		this.Property(t => t.Author).HasColumnName("Author").IsUnicode(false).HasMaxLength(150);
    		this.Property(t => t.Uploader).HasColumnName("Uploader").IsUnicode(false).HasMaxLength(150);
    		this.Property(t => t.BigPicture).HasColumnName("BigPicture").IsUnicode(false).HasMaxLength(2048);
    		this.Property(t => t.SmallPicture).HasColumnName("SmallPicture").IsUnicode(false).HasMaxLength(2048);
    		this.Property(t => t.Description).HasColumnName("Description");
    		this.Property(t => t.ProviderVoteCount).HasColumnName("ProviderVoteCount");
    		this.HasRequired(t => t.Content).WithOptional(t => t.VideoContent);
    		this.HasOptional(t => t.VideoProvider).WithMany(t => t.VideoContents).HasForeignKey(d => d.ProviderID);
    	}
    }
}
